import { Resend } from 'resend';

interface EmailParams {
    to: string;
    subject: string;
    html: string;
    apiKey?: string | null;
}

export async function sendEmail({ to, subject, html, apiKey }: EmailParams) {
    // Priority: Passed API Key > Global Env
    const key = apiKey || process.env.RESEND_API_KEY;

    if (!key) {
        console.warn('RESEND_API_KEY is not set (and no tenant key provided). Email not sent.');
        console.log(`[Mock Email] To: ${to}, Subject: ${subject}, Content: ${html.substring(0, 100)}...`);
        return { success: true, mock: true };
    }

    try {
        const resend = new Resend(key);
        const data = await resend.emails.send({
            from: 'Dispatch SaaS <no-reply@taximarketingservices.co.uk>',
            to,
            subject,
            html,
        });

        if (data.error) {
            console.error('Resend API Error:', data.error);
            return { success: false, error: data.error };
        }

        return { success: true, data };
    } catch (error) {
        console.error('Failed to send email:', error);
        return { success: false, error };
    }
}

export const getResetPasswordEmail = (resetLink: string, brandColor: string = '#f59e0b', logoUrl: string = '') => `
    <div style="font-family: sans-serif; max-w-md; margin: 0 auto;">
        ${logoUrl ? `<div style="text-align: center; margin-bottom: 20px;"><img src="${logoUrl}" alt="Company Logo" style="max-height: 50px;" /></div>` : ''}
        <h2>Reset Your Password</h2>
        <p>You requested a password reset for your account.</p>
        <p>Click the link below to set a new password:</p>
        <a href="${resetLink}" style="display: inline-block; background: ${brandColor}; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; margin: 20px 0;">Reset Password</a>
        <p style="font-size: 12px; color: #666;">This link expires in 1 hour. If you didn't request this, please ignore this email.</p>
    </div>
`;

export const getWelcomeEmail = (name: string, loginUrl: string, email: string, tempPass: string, brandColor: string = '#f59e0b', logoUrl: string = '') => `
    <div style="font-family: sans-serif; max-w-md; margin: 0 auto;">
        ${logoUrl ? `<div style="text-align: center; margin-bottom: 20px;"><img src="${logoUrl}" alt="Company Logo" style="max-height: 50px;" /></div>` : ''}
        <h2>Welcome to the Team, ${name}!</h2>
        <p>An account has been created for you.</p>
        <div style="background: #f4f4f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p><strong>Login URL:</strong> <a href="${loginUrl}" style="color: ${brandColor};">${loginUrl}</a></p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Temporary Password:</strong> ${tempPass}</p>
        </div>
        <p>Please log in and change your password immediately.</p>
    </div>
`;

export const getPassengerReceiptEmail = (
    tenantName: string,
    jobId: string,
    pickup: string,
    dropoff: string,
    time: string,
    price: string,
    brandColor: string = '#f59e0b',
    logoUrl: string = ''
) => `
    <div style="font-family: sans-serif; max-w: 600px; margin: 0 auto; color: #333;">
        ${logoUrl ? `<div style="text-align: center; margin-bottom: 30px;"><img src="${logoUrl}" alt="${tenantName} Logo" style="max-height: 60px;" /></div>` : `<h1 style="text-align: center; color: ${brandColor};">${tenantName}</h1>`}
        <h2 style="border-bottom: 2px solid ${brandColor}; padding-bottom: 10px;">Booking Receipt</h2>
        <p>Thank you for booking with us. Your journey details are below.</p>
        
        <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0; color: ${brandColor};">Booking REF: #${jobId}</h3>
            <table style="width: 100%; border-collapse: collapse;">
                <tr><td style="padding: 8px 0; border-bottom: 1px solid #ddd;"><strong>Date/Time:</strong></td><td style="padding: 8px 0; text-align: right; border-bottom: 1px solid #ddd;">${new Date(time).toLocaleString()}</td></tr>
                <tr><td style="padding: 8px 0; border-bottom: 1px solid #ddd;"><strong>Pickup:</strong></td><td style="padding: 8px 0; text-align: right; border-bottom: 1px solid #ddd;">${pickup}</td></tr>
                <tr><td style="padding: 8px 0; border-bottom: 1px solid #ddd;"><strong>Dropoff:</strong></td><td style="padding: 8px 0; text-align: right; border-bottom: 1px solid #ddd;">${dropoff}</td></tr>
                <tr><td style="padding: 12px 0 0 0; font-size: 1.2em;"><strong>Total Fare:</strong></td><td style="padding: 12px 0 0 0; font-size: 1.2em; text-align: right; color: ${brandColor};"><strong>${price}</strong></td></tr>
            </table>
        </div>
        <p style="font-size: 12px; color: #888; text-align: center; margin-top: 30px;">This is an automated receipt generated by the Dispatch Platform.</p>
    </div>
`;

export const getSupportEscalationEmail = (ticketId: string, tenantName: string, subject: string, brandColor: string = '#ef4444', logoUrl: string = '') => `
    <div style="font-family: sans-serif; max-w: 600px; margin: 0 auto; color: #333;">
        ${logoUrl ? `<div style="text-align: center; margin-bottom: 20px;"><img src="${logoUrl}" alt="${tenantName} Logo" style="max-height: 50px;" /></div>` : ''}
        <h2 style="color: ${brandColor};">Support Ticket Escalated 🚨</h2>
        <p>The AI Support Agent for <strong>${tenantName}</strong> has escalated a ticket to human support.</p>
        
        <div style="background: #fef2f2; border: 1px solid #fca5a5; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <p style="margin: 0 0 10px 0;"><strong>Ticket ID:</strong> ${ticketId}</p>
            <p style="margin: 0;"><strong>Subject:</strong> ${subject}</p>
        </div>
        
        <p>Please log in to the Super Admin console to review the chat transcript and reply to the user.</p>
        <a href="https://app.cabai.co.uk/admin/support/${ticketId}" style="display: inline-block; background: ${brandColor}; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; margin-top: 10px;">View Ticket in Admin Console</a>
    </div>
`;
